return function(theme)
  return {
    -- vim highlights
    Normal                             = { fg = theme.base05, bg = theme.base00, sp = nil, ctermfg = theme.cterm05, ctermbg = theme.cterm00 },
    Bold                               = { fg = nil, bg = nil, bold = true, sp = nil, ctermfg = nil, ctermbg = nil },
    Debug                              = { fg = theme.base08, bg = nil, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    Directory                          = { fg = theme.base0D, bg = nil, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    Error                              = { fg = theme.base08, bg = theme.base00, sp = nil, ctermfg = theme.cterm08, ctermbg = theme.cterm00 },
    ErrorMsg                           = { fg = theme.base08, bg = theme.base00, sp = nil, ctermfg = theme.cterm08, ctermbg = theme.cterm00 },
    Exception                          = { fg = theme.base08, bg = nil, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    FoldColumn                         = { fg = theme.base0C, bg = theme.base00, sp = nil, ctermfg = theme.cterm0C, ctermbg = theme.cterm00 },
    Folded                             = { fg = theme.base03, bg = theme.base01, sp = nil, ctermfg = theme.cterm03, ctermbg = theme.cterm01 },
    IncSearch                          = { fg = theme.base01, bg = theme.base09, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm01, ctermbg = theme.cterm09 },
    Italic                             = { fg = nil, bg = nil, italic = true, sp = nil, ctermfg = nil, ctermbg = nil },
    Macro                              = { fg = theme.base08, bg = nil, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    MatchParen                         = { fg = nil, bg = theme.base03, sp = nil, ctermfg = nil, ctermbg = theme.cterm03 },
    ModeMsg                            = { fg = theme.base0B, bg = nil, sp = nil, ctermfg = theme.cterm0B, ctermbg = nil },
    MoreMsg                            = { fg = theme.base0B, bg = nil, sp = nil, ctermfg = theme.cterm0B, ctermbg = nil },
    Question                           = { fg = theme.base0D, bg = nil, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    Search                             = { fg = theme.base01, bg = theme.base0A, sp = nil, ctermfg = theme.cterm01, ctermbg = theme.cterm0A },
    Substitute                         = { fg = theme.base01, bg = theme.base0A, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm01, ctermbg = theme.cterm0A },
    SpecialKey                         = { fg = theme.base03, bg = nil, sp = nil, ctermfg = theme.cterm03, ctermbg = nil },
    TooLong                            = { fg = theme.base08, bg = nil, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    Underlined                         = { fg = theme.base08, bg = nil, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    Visual                             = { fg = nil, bg = theme.base02, sp = nil, ctermfg = nil, ctermbg = theme.cterm02 },
    VisualNOS                          = { fg = theme.base08, bg = nil, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    WarningMsg                         = { fg = theme.base08, bg = nil, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    WildMenu                           = { fg = theme.base08, bg = theme.base0A, sp = nil, ctermfg = theme.cterm08, ctermbg = theme.cterm0A },
    Title                              = { fg = theme.base0D, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    Conceal                            = { fg = theme.base0D, bg = theme.base00, sp = nil, ctermfg = theme.cterm0D, ctermbg = theme.cterm00 },
    Cursor                             = { fg = theme.base00, bg = theme.base05, sp = nil, ctermfg = theme.cterm00, ctermbg = theme.cterm05 },
    NonText                            = { fg = theme.base03, bg = nil, sp = nil, ctermfg = theme.cterm03, ctermbg = nil },
    LineNr                             = { fg = theme.base03, bg = theme.base00, sp = nil, ctermfg = theme.cterm04, ctermbg = theme.cterm00 },
    SignColumn                         = { fg = theme.base04, bg = theme.base00, sp = nil, ctermfg = theme.cterm04, ctermbg = theme.cterm00 },
    StatusLine                         = { fg = theme.base05, bg = theme.base02, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = theme.cterm02 },
    StatusLineNC                       = { fg = theme.base04, bg = theme.base01, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm04, ctermbg = theme.cterm01 },
    WinBar                             = { fg = theme.base05, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = nil },
    WinBarNC                           = { fg = theme.base04, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm04, ctermbg = nil },
    VertSplit                          = { fg = theme.base05, bg = theme.base00, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = theme.cterm00 },
    ColorColumn                        = { fg = nil, bg = theme.base01, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = nil, ctermbg = theme.cterm01 },
    CursorColumn                       = { fg = nil, bg = theme.base01, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = nil, ctermbg = theme.cterm01 },
    CursorLine                         = { fg = nil, bg = theme.base01, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = nil, ctermbg = theme.cterm01 },
    CursorLineNr                       = { fg = theme.base04, bg = theme.base01, sp = nil, ctermfg = theme.cterm04, ctermbg = theme.cterm01 },
    QuickFixLine                       = { fg = nil, bg = theme.base01, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = nil, ctermbg = theme.cterm01 },
    PMenu                              = { fg = theme.base05, bg = theme.base01, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = theme.cterm01 },
    PMenuSel                           = { fg = theme.base01, bg = theme.base05, sp = nil, ctermfg = theme.cterm01, ctermbg = theme.cterm05 },
    TabLine                            = { fg = theme.base03, bg = theme.base01, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm03, ctermbg = theme.cterm01 },
    TabLineFill                        = { fg = theme.base03, bg = theme.base01, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm03, ctermbg = theme.cterm01 },
    TabLineSel                         = { fg = theme.base0B, bg = theme.base01, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0B, ctermbg = theme.cterm01 },

    -- Standard syntax hlighting
    Boolean                            = { fg = theme.base09, bg = nil, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    Character                          = { fg = theme.base08, bg = nil, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    Comment                            = { fg = theme.base03, bg = nil, sp = nil, ctermfg = theme.cterm03, ctermbg = nil },
    Conditional                        = { fg = theme.base0E, bg = nil, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    Constant                           = { fg = theme.base09, bg = nil, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    Define                             = { fg = theme.base0E, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    Delimiter                          = { fg = theme.base0F, bg = nil, sp = nil, ctermfg = theme.cterm0F, ctermbg = nil },
    Float                              = { fg = theme.base09, bg = nil, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    Function                           = { fg = theme.base0D, bg = nil, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    Identifier                         = { fg = theme.base08, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    Include                            = { fg = theme.base0D, bg = nil, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    Keyword                            = { fg = theme.base0E, bg = nil, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    Label                              = { fg = theme.base0A, bg = nil, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    Number                             = { fg = theme.base09, bg = nil, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    Operator                           = { fg = theme.base0E, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    PreProc                            = { fg = theme.base0A, bg = nil, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    Repeat                             = { fg = theme.base0A, bg = nil, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    Special                            = { fg = theme.base0C, bg = nil, sp = nil, ctermfg = theme.cterm0C, ctermbg = nil },
    SpecialChar                        = { fg = theme.base0F, bg = nil, sp = nil, ctermfg = theme.cterm0F, ctermbg = nil },
    Statement                          = { fg = theme.base08, bg = nil, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    StorageClass                       = { fg = theme.base0A, bg = nil, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    String                             = { fg = theme.base0B, bg = nil, sp = nil, ctermfg = theme.cterm0B, ctermbg = nil },
    Structure                          = { fg = theme.base0E, bg = nil, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    Tag                                = { fg = theme.base0A, bg = nil, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    Todo                               = { fg = theme.base0A, bg = theme.base01, sp = nil, ctermfg = theme.cterm0A, ctermbg = theme.cterm01 },
    Type                               = { fg = theme.base0A, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    Typedef                            = { fg = theme.base0A, bg = nil, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },

    -- Diff hlighting
    DiffAdd                            = { fg = theme.base0B, bg = theme.base00, sp = nil, ctermfg = theme.cterm0B, ctermbg = theme.cterm00 },
    DiffChange                         = { fg = theme.base03, bg = theme.base00, sp = nil, ctermfg = theme.cterm03, ctermbg = theme.cterm00 },
    DiffDelete                         = { fg = theme.base08, bg = theme.base00, sp = nil, ctermfg = theme.cterm08, ctermbg = theme.cterm00 },
    DiffText                           = { fg = theme.base0D, bg = theme.base00, sp = nil, ctermfg = theme.cterm0D, ctermbg = theme.cterm00 },
    DiffAdded                          = { fg = theme.base0B, bg = theme.base00, sp = nil, ctermfg = theme.cterm0B, ctermbg = theme.cterm00 },
    DiffFile                           = { fg = theme.base08, bg = theme.base00, sp = nil, ctermfg = theme.cterm08, ctermbg = theme.cterm00 },
    DiffNewFile                        = { fg = theme.base0B, bg = theme.base00, sp = nil, ctermfg = theme.cterm0B, ctermbg = theme.cterm00 },
    DiffLine                           = { fg = theme.base0D, bg = theme.base00, sp = nil, ctermfg = theme.cterm0D, ctermbg = theme.cterm00 },
    DiffRemoved                        = { fg = theme.base08, bg = theme.base00, sp = nil, ctermfg = theme.cterm08, ctermbg = theme.cterm00 },

    -- Git hlighting
    gitcommitOverflow                  = { fg = theme.base08, bg = nil, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    gitcommitSummary                   = { fg = theme.base0B, bg = nil, sp = nil, ctermfg = theme.cterm0B, ctermbg = nil },
    gitcommitComment                   = { fg = theme.base03, bg = nil, sp = nil, ctermfg = theme.cterm03, ctermbg = nil },
    gitcommitUntracked                 = { fg = theme.base03, bg = nil, sp = nil, ctermfg = theme.cterm03, ctermbg = nil },
    gitcommitDiscarded                 = { fg = theme.base03, bg = nil, sp = nil, ctermfg = theme.cterm03, ctermbg = nil },
    gitcommitSelected                  = { fg = theme.base03, bg = nil, sp = nil, ctermfg = theme.cterm03, ctermbg = nil },
    gitcommitHeader                    = { fg = theme.base0E, bg = nil, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    gitcommitSelectedType              = { fg = theme.base0D, bg = nil, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    gitcommitUnmergedType              = { fg = theme.base0D, bg = nil, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    gitcommitDiscardedType             = { fg = theme.base0D, bg = nil, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    gitcommitBranch                    = { fg = theme.base09, bg = nil, bold = true, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    gitcommitUntrackedFile             = { fg = theme.base0A, bg = nil, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    gitcommitUnmergedFile              = { fg = theme.base08, bg = nil, bold = true, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    gitcommitDiscardedFile             = { fg = theme.base08, bg = nil, bold = true, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    gitcommitSelectedFile              = { fg = theme.base0B, bg = nil, bold = true, sp = nil, ctermfg = theme.cterm0B, ctermbg = nil },

    -- GitGutter hlighting
    GitGutterAdd                       = { fg = theme.base0B, bg = theme.base00, sp = nil, ctermfg = theme.cterm0B, ctermbg = theme.cterm00 },
    GitGutterChange                    = { fg = theme.base0D, bg = theme.base00, sp = nil, ctermfg = theme.cterm0D, ctermbg = theme.cterm00 },
    GitGutterDelete                    = { fg = theme.base08, bg = theme.base00, sp = nil, ctermfg = theme.cterm08, ctermbg = theme.cterm00 },
    GitGutterChangeDelete              = { fg = theme.base0E, bg = theme.base00, sp = nil, ctermfg = theme.cterm0E, ctermbg = theme.cterm00 },

    -- Spelling hlighting
    SpellBad                           = { fg = nil, bg = nil, undercurl = true, sp = theme.base08, ctermfg = nil, ctermbg = nil },
    SpellLocal                         = { fg = nil, bg = nil, undercurl = true, sp = theme.base0C, ctermfg = nil, ctermbg = nil },
    SpellCap                           = { fg = nil, bg = nil, undercurl = true, sp = theme.base0D, ctermfg = nil, ctermbg = nil },
    SpellRare                          = { fg = nil, bg = nil, undercurl = true, sp = theme.base0E, ctermfg = nil, ctermbg = nil },

    DiagnosticError                    = { fg = theme.base08, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    DiagnosticWarn                     = { fg = theme.base0E, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    DiagnosticInfo                     = { fg = theme.base0D, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    Diagnostict                        = { fg = theme.base0C, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0C, ctermbg = nil },
    DiagnosticUnderlineError           = { fg = nil, bg = nil, undercurl = true, sp = theme.base08, ctermfg = nil, ctermbg = nil },
    DiagnosticUnderlineWarning         = { fg = nil, bg = nil, undercurl = true, sp = theme.base0E, ctermfg = nil, ctermbg = nil },
    DiagnosticUnderlineWarn            = { fg = nil, bg = nil, undercurl = true, sp = theme.base0E, ctermfg = nil, ctermbg = nil },
    DiagnosticUnderlineInformation     = { fg = nil, bg = nil, undercurl = true, sp = theme.base0F, ctermfg = nil, ctermbg = nil },
    DiagnosticUnderlinet               = { fg = nil, bg = nil, undercurl = true, sp = theme.base0C, ctermfg = nil, ctermbg = nil },

    LspReferenceText                   = { fg = nil, bg = nil, underline = true, sp = theme.base04, ctermfg = nil, ctermbg = nil },
    LspReferenceRead                   = { fg = nil, bg = nil, underline = true, sp = theme.base04, ctermfg = nil, ctermbg = nil },
    LspReferenceWrite                  = { fg = nil, bg = nil, underline = true, sp = theme.base04, ctermfg = nil, ctermbg = nil },
    LspDiagnosticsDefaultError         = { link = 'DiagnosticError' },
    LspDiagnosticsDefaultWarning       = { link = 'DiagnosticWarn' },
    LspDiagnosticsDefaultInformation   = { link = 'DiagnosticInfo' },
    LspDiagnosticsDefaultt             = { link = 'Diagnostict' },
    LspDiagnosticsUnderlineError       = { link = 'DiagnosticUnderlineError' },
    LspDiagnosticsUnderlineWarning     = { link = 'DiagnosticUnderlineWarning' },
    LspDiagnosticsUnderlineInformation = { link = 'DiagnosticUnderlineInformation' },
    LspDiagnosticsUnderlinet           = { link = 'DiagnosticUnderlinet' },

    TSAnnotation                       = { fg = theme.base0F, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0F, ctermbg = nil },
    TSAttribute                        = { fg = theme.base0A, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    TSBoolean                          = { fg = theme.base09, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    TSCharacter                        = { fg = theme.base08, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    TSComment                          = { fg = theme.base03, bg = nil, italic = true, sp = nil, ctermfg = theme.cterm03, ctermbg = nil },
    TSConstructor                      = { fg = theme.base0D, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    TSConditional                      = { fg = theme.base0E, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    TSConstant                         = { fg = theme.base09, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    TSConstBuiltin                     = { fg = theme.base09, bg = nil, italic = true, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    TSConstMacro                       = { fg = theme.base08, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    TSError                            = { fg = theme.base08, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    TSException                        = { fg = theme.base08, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    TSField                            = { fg = theme.base05, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = nil },
    TSFloat                            = { fg = theme.base09, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    TSFunction                         = { fg = theme.base0D, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    TSFuncBuiltin                      = { fg = theme.base0D, bg = nil, italic = true, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    TSFuncMacro                        = { fg = theme.base08, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    TSInclude                          = { fg = theme.base0D, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    TSKeyword                          = { fg = theme.base0E, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    TSKeywordFunction                  = { fg = theme.base0E, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    TSKeywordOperator                  = { fg = theme.base0E, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    TSLabel                            = { fg = theme.base0A, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    TSMethod                           = { fg = theme.base0D, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    TSNamespace                        = { fg = theme.base08, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    TSNone                             = { fg = theme.base05, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = nil },
    TSNumber                           = { fg = theme.base09, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    TSOperator                         = { fg = theme.base05, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = nil },
    TSParameter                        = { fg = theme.base05, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = nil },
    TSParameterReference               = { fg = theme.base05, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = nil },
    TSProperty                         = { fg = theme.base05, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = nil },
    TSPunctDelimiter                   = { fg = theme.base0F, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0F, ctermbg = nil },
    TSPunctBracket                     = { fg = theme.base05, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = nil },
    TSPunctSpecial                     = { fg = theme.base0F, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0F, ctermbg = nil },
    TSRepeat                           = { fg = theme.base0E, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0E, ctermbg = nil },
    TSString                           = { fg = theme.base0B, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0B, ctermbg = nil },
    TSStringRegex                      = { fg = theme.base0C, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0C, ctermbg = nil },
    TSStringEscape                     = { fg = theme.base0C, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0C, ctermbg = nil },
    TSSymbol                           = { fg = theme.base0B, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0B, ctermbg = nil },
    TSTag                              = { fg = theme.base08, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    TSTagDelimiter                     = { fg = theme.base0F, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0F, ctermbg = nil },
    TSText                             = { fg = theme.base05, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm05, ctermbg = nil },
    TSStrong                           = { fg = nil, bg = nil, bold = true, sp = nil, ctermfg = nil, ctermbg = nil },
    TSEmphasis                         = { fg = theme.base09, bg = nil, italic = true, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    TSUnderline                        = { fg = theme.base00, bg = nil, underline = true, sp = nil, ctermfg = theme.cterm00, ctermbg = nil },
    TSStrike                           = { fg = theme.base00, bg = nil, strikethrough = true, sp = nil, ctermfg = theme.cterm00, ctermbg = nil },
    TSTitle                            = { fg = theme.base0D, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0D, ctermbg = nil },
    TSLiteral                          = { fg = theme.base09, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    TSURI                              = { fg = theme.base09, bg = nil, underline = true, sp = nil, ctermfg = theme.cterm09, ctermbg = nil },
    TSType                             = { fg = theme.base0A, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    TSTypeBuiltin                      = { fg = theme.base0A, bg = nil, italic = true, sp = nil, ctermfg = theme.cterm0A, ctermbg = nil },
    TSVariable                         = { fg = theme.base08, bg = nil, bold = false, italic = false, underline = false, undercurl = false, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },
    TSVariableBuiltin                  = { fg = theme.base08, bg = nil, italic = true, sp = nil, ctermfg = theme.cterm08, ctermbg = nil },

    TSDefinition                       = { fg = nil, bg = nil, underline = true, sp = theme.base04, ctermfg = nil, ctermbg = nil },
    TSDefinitionUsage                  = { fg = nil, bg = nil, underline = true, sp = theme.base04, ctermfg = nil, ctermbg = nil },
    TSCurrentScope                     = { fg = nil, bg = nil, bold = true, sp = nil, ctermfg = nil, ctermbg = nil },

    LspInlayt                          = { fg = theme.base03, bg = nil, italic = true, sp = nil, ctermfg = theme.cterm03, ctermbg = nil },

    ['@comment']                       = { link = 'TSComment' },
    ['@error']                         = { link = 'TSError' },
    ['@none']                          = { link = 'TSNone' },
    ['@preproc']                       = { link = 'PreProc' },
    ['@define']                        = { link = 'Define' },
    ['@operator']                      = { link = 'TSOperator' },
    ['@punctuation.delimiter']         = { link = 'TSPunctDelimiter' },
    ['@punctuation.bracket']           = { link = 'TSPunctBracket' },
    ['@punctuation.special']           = { link = 'TSPunctSpecial' },
    ['@string']                        = { link = 'TSString' },
    ['@string.regex']                  = { link = 'TSStringRegex' },
    ['@string.escape']                 = { link = 'TSStringEscape' },
    ['@string.special']                = { link = 'SpecialChar' },
    ['@character']                     = { link = 'TSCharacter' },
    ['@character.special']             = { link = 'SpecialChar' },
    ['@boolean']                       = { link = 'TSBoolean' },
    ['@number']                        = { link = 'TSNumber' },
    ['@float']                         = { link = 'TSFloat' },
    ['@function']                      = { link = 'TSFunction' },
    ['@function.call']                 = { link = 'TSFunction' },
    ['@function.builtin']              = { link = 'TSFuncBuiltin' },
    ['@function.macro']                = { link = 'TSFuncMacro' },
    ['@method']                        = { link = 'TSMethod' },
    ['@method.call']                   = { link = 'TSMethod' },
    ['@constructor']                   = { link = 'TSConstructor' },
    ['@parameter']                     = { link = 'TSParameter' },
    ['@keyword']                       = { link = 'TSKeyword' },
    ['@keyword.function']              = { link = 'TSKeywordFunction' },
    ['@keyword.operator']              = { link = 'TSKeywordOperator' },
    ['@keyword.return']                = { link = 'TSKeyword' },
    ['@conditional']                   = { link = 'TSConditional' },
    ['@repeat']                        = { link = 'TSRepeat' },
    ['@debug']                         = { link = 'Debug' },
    ['@label']                         = { link = 'TSLabel' },
    ['@include']                       = { link = 'TSInclude' },
    ['@exception']                     = { link = 'TSException' },
    ['@type']                          = { link = 'TSType' },
    ['@type.builtin']                  = { link = 'TSTypeBuiltin' },
    ['@type.qualifier']                = { link = 'TSKeyword' },
    ['@type.definition']               = { link = 'TSType' },
    ['@storageclass']                  = { link = 'StorageClass' },
    ['@attribute']                     = { link = 'TSAttribute' },
    ['@field']                         = { link = 'TSField' },
    ['@property']                      = { link = 'TSProperty' },
    ['@variable']                      = { link = 'TSVariable' },
    ['@variable.builtin']              = { link = 'TSVariableBuiltin' },
    ['@constant']                      = { link = 'TSConstant' },
    ['@constant.builtin']              = { link = 'TSConstant' },
    ['@constant.macro']                = { link = 'TSConstant' },
    ['@namespace']                     = { link = 'TSNamespace' },
    ['@symbol']                        = { link = 'TSSymbol' },
    ['@text']                          = { link = 'TSText' },
    ['@text.diff.add']                 = { link = 'DiffAdd' },
    ['@text.diff.delete']              = { link = 'DiffDelete' },
    ['@text.strong']                   = { link = 'TSStrong' },
    ['@text.emphasis']                 = { link = 'TSEmphasis' },
    ['@text.underline']                = { link = 'TSUnderline' },
    ['@text.strike']                   = { link = 'TSStrike' },
    ['@text.title']                    = { link = 'TSTitle' },
    ['@text.literal']                  = { link = 'TSLiteral' },
    ['@text.uri']                      = { link = 'TSUri' },
    ['@text.math']                     = { link = 'Number' },
    ['@text.environment']              = { link = 'Macro' },
    ['@text.environment.name']         = { link = 'Type' },
    ['@text.reference']                = { link = 'TSParameterReference' },
    ['@text.todo']                     = { link = 'Todo' },
    ['@text.note']                     = { link = 'Tag' },
    ['@text.warning']                  = { link = 'DiagnosticWarn' },
    ['@text.danger']                   = { link = 'DiagnosticError' },
    ['@tag']                           = { link = 'TSTag' },
    ['@tag.attribute']                 = { link = 'TSAttribute' },
    ['@tag.delimiter']                 = { link = 'TSTagDelimiter' },

    ['@function.method']               = { link = '@method' },
    ['@function.method.call']          = { link = '@method.call' },
    ['@comment.error']                 = { link = '@text.danger' },
    ['@comment.warning']               = { link = '@text.warning' },
    ['@comment.hint']                  = { link = 'DiagnosticHint' },
    ['@comment.info']                  = { link = 'DiagnosticInfo' },
    ['@comment.todo']                  = { link = '@text.todo' },
    ['@diff.plus']                     = { link = '@text.diff.add' },
    ['@diff.minus']                    = { link = '@text.diff.delete' },
    ['@diff.delta']                    = { link = 'DiffChange' },
    ['@string.special.url']            = { link = '@text.uri' },
    ['@keyword.directive']             = { link = '@preproc' },
    ['@keyword.directive.define']      = { link = '@define' },
    ['@keyword.storage']               = { link = '@storageclass' },
    ['@keyword.conditional']           = { link = '@conditional' },
    ['@keyword.debug']                 = { link = '@debug' },
    ['@keyword.exception']             = { link = '@exception' },
    ['@keyword.import']                = { link = '@include' },
    ['@keyword.repeat']                = { link = '@repeat' },
    ['@variable.parameter']            = { link = '@parameter' },
    ['@variable.member']               = { link = '@field' },
    ['@module']                        = { link = '@namespace' },
    ['@number.float']                  = { link = '@float' },
    ['@string.special.symbol']         = { link = '@symbol' },
    ['@string.regexp']                 = { link = '@string.regex' },
    ['@markup.strong']                 = { link = '@text.strong' },
    ['@markup.italic']                 = { link = 'Italic' },
    ['@markup.strikethrough']          = { link = '@text.strikethrough' },
    ['@markup.heading']                = { link = '@text.title' },
    ['@markup.raw']                    = { link = '@text.literal' },
    ['@markup.link']                   = { link = '@text.reference' },
    ['@markup.link.url']               = { link = '@text.uri' },
    ['@markup.link.label']             = { link = '@string.special' },
    ['@markup.list']                   = { link = '@punctuation.special' },
  }
end
